### ISSUE TITLE
Take advangate of resty.core, and an init file

### ISSUE THREAD

**Issue by bungle** [kronometrix/kernel#19]
I propose to add this line to nginx.conf:

```
init_by_lua_file "../app/init.lua"
```

Just before line (https://github.com/kronometrix/kernel/blob/master/config/freebsd/nginx.conf.maas#L28):

```
init_worker_by_lua_file "../app/timer.lua";
```

`resty.core` is faster and better JIT compiles. Also there may be need for other init code as well.

(Same for Linux version as well)

**Comment by sparvu** [comment]
fixed.
