### ISSUE TITLE
analytics/kernel add smtp library in kernel

### ISSUE THREAD

**Issue by irimiab** [kronometrix/kernel#7]
To be able to send ALERT notification e-mails, I need the SMTP library in kernel. It is already included in "auth" layer. Please integrate it in "kernel" layer also.

**Comment by sparvu** [comment]
isnt possible we pass this to the auth layer for all notifications since we have there all needed bits ? The kernel should not be involved in email processing , right ? Cant we just add for the internal API another call which makes a call to the auth ? Ideas ?

**Comment by irimiab** [comment]
Why shouldn't it be involved in e-mail sending?

**Comment by sparvu** [comment]
we keep kernel for: DPM, DSM and all efforts of data numerical processing. (On top of that we have the UI part and the extensions modernization). All the rest we should pass it to the module where we have already: user management and notification, SMTP, etc 

We need to keep things simple and have an internal private API between auth and kernel as we discussed.

**Comment by sparvu** [comment]
I will think to see what pro cons are for email notification within kernel space ... later on more details. If you are aware of issues let me know. Comment here. Im available in phone in 15mins

**Comment by irimiab** [comment]
I checked for the possibility to keep the e-mail sending code only in the "auth" layer. I have these issues:
- in the private API **we don't have requests from "kernel" to "auth"**; only *forward* ("auth" to "kernel") requests are implemented
- to implement *reverse* private API requests, the "kernel" layer has to use a resolver and must have the right routes configured (routes to "auth" layer). Basically, it's not simpler that actually making an SMTP send request by itself

**Comment by sparvu** [comment]
resolver here means DNS resolver or ?

**Comment by sparvu** [comment]
We should have standard SMTP services offered by a single certain layer within appliance. We need to have a clear utility provider for services like, SMTP for example. Which should be used by all our modules when it is needed. We dont want our kernel make SMTP and DNS calls.

So we dont have any calls from kernel to auth now, at this moment ?

**Comment by irimiab** [comment]
No

**Comment by sparvu** [comment]
Well, this is an important part of design. As we said auth has user mgmt + other services within, including SMTP. So we need to have private calls which can send email notifications. This should be available from auth, kernel.

Options:

1. Make kernel to have routes towards the auth instance for smtp calls

2. Make a separate http instance and offer for SMTP and other utility services a private API which can be called by auth, kernel etc 

3. ?

**Comment by irimiab** [comment]
Not valid anymore
